development:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: rbs400rbs

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: rbs400rbs

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: rbs400rbs
cucumber:
  <<: *test
